# read the doc: https://huggingface.co/docs/hub/spaces-sdks-docker
# you will also find guides on how best to write your Dockerfile

FROM nvidia/cuda:12.6.2-base-ubuntu22.04

WORKDIR /code

RUN apt-get update
RUN apt install -y zip

# Install .NET SDK
RUN apt-get update
RUN apt-get install -y dotnet-sdk-8.0
RUN apt-get install -y aspnetcore-runtime-8.0
RUN apt-get install -y cmake
RUN apt-get install -y git-lfs

RUN cat /etc/os-release
RUN apt-get install -y software-properties-common

# Clone and build Seq2SeqSharp
RUN git clone https://github.com/zhongkaifu/Seq2SeqSharp.git
WORKDIR /code/Seq2SeqSharp
RUN dotnet build Seq2SeqSharp.sln --configuration Release

# Clone and build ChatBot
WORKDIR /code
RUN git clone https://github.com/zhongkaifu/ChatBot.git
WORKDIR /code/ChatBot
RUN dotnet build Chatbot.sln --configuration Release
RUN dotnet publish Chatbot.sln --configuration Release

RUN apt-get install -y build-essential

# Build customized SentencePiece
WORKDIR /code/Seq2SeqSharp/ExternalProjects
RUN unzip SentencePiece.zip
WORKDIR /code/Seq2SeqSharp/ExternalProjects/SentencePiece
RUN mkdir build
WORKDIR /code/Seq2SeqSharp/ExternalProjects/SentencePiece/build
RUN cmake ..
RUN make -j4
RUN make install
RUN ldconfig -v

# Install Cuda
RUN apt install wget
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
RUN dpkg -i cuda-keyring_1.1-1_all.deb
RUN apt-get update
RUN apt-get -y install cuda-toolkit-12-6

WORKDIR /code

RUN mkdir -p /code/bin
RUN chmod 777 /code/bin
WORKDIR /code/bin

# Deploy models, vocabulary and config files
RUN cp -r /code/ChatBot/Chatbot/bin/Release/net8.0/publish/* .
RUN wget https://huggingface.co/zhongkaifu/letschat.health/resolve/main/ybook_chat_7b.model.308000.FLOAT16
RUN wget https://huggingface.co/zhongkaifu/letschat.health/resolve/main/chsSpm.model
RUN wget https://huggingface.co/zhongkaifu/letschat.health/resolve/main/cuda_fp16.h
RUN wget https://huggingface.co/zhongkaifu/letschat.health/resolve/main/cuda_fp16.hpp
RUN rm appsettings.json
RUN wget https://huggingface.co/zhongkaifu/letschat.health/resolve/main/appsettings.json

# ENV MKL_ENABLE_INSTRUCTIONS=AVX2

# Run application
CMD ["dotnet","/code/bin/Chatbot.dll"]